export default {
    public:{
        SEARCHSUGGEST:"SEARCHSUGGEST",
        SEARCH:"SEARCH",
        LOGINMOBI:"LOGINMOBI",
        LOGINEMAIL:"LOGINEMAIL",
        USERINFO:"USERINFO",
        PLAYLIST:"PLAYLIST"
    },
    music:{
        recommend:{
            BANNER:"BANNER",
            RECLIST:"RECLIST",
            EXCLUSIVE:"EXCLUSIVE",
            NEWTEST:"NEWTEST",
            RECMV:"RECMV"
        },
        playList:{
            TAGLIST:"TAGLIST",
            HOTTAG:"HOTTAG",
            ALLTAG:"ALLTAG",            
        },
        ranking:{
            RANKING_SUGRE:"RANKING_SURGE",
            RANKING_NEW:"RANKING_NEW",
            RANKING_ORIGINAL:"RANKING_ORIGINAL",
            RANKING_HOT:"RANKING_HOT"
        }
    }
}