export default {
    public:{
        SEARCHSUGGEST:"SEARCHSUGGEST",
        SEARCH:"SEARCH",
        LOGINMOBI:"LOGINMOBI",
        LOGINEMAIL:"LOGINEMAIL",
        USERINFO:"USERINFO",
        PLAYLIST:"PLAYLIST"
    },
    music:{
        recommend:{
            BANNER:"BANNER",
            RECLIST:"RECLIST",
            EXCLUSIVE:"EXCLUSIVE",
            NEWTEST:"NEWTEST",
            RECMV:"RECMV"
        }
    }
}