export default {
    public:{
        SEARCHSUGGEST:"SEARCHSUGGEST",
        SEARCH:"SEARCH",
        LOGINMOBI:"LOGINMOBI",
        LOGINEMAIL:"LOGINEMAIL",
        USERINFO:"USERINFO",
        PLAYLIST:"PLAYLIST",
        MUSIC_URL:"MUSIC_URL",
        MUSIC_LYRIC:"MUSIC_LYRIC",
        MUSIC_INFO:"MUSIC_INFO",
        MUSIC_COMMENT:"MUSIC_COMMENT"
    },
    music:{
        recommend:{
            BANNER:"BANNER",
            RECLIST:"RECLIST",
            EXCLUSIVE:"EXCLUSIVE",
            NEWTEST:"NEWTEST",
            RECMV:"RECMV"
        },
        playList:{
            TAGLIST:"TAGLIST",
            HOTTAG:"HOTTAG",
            ALLTAG:"ALLTAG",            
        },
        ranking:{
            RANKING_SUGRE:"RANKING_SURGE",
            RANKING_NEW:"RANKING_NEW",
            RANKING_ORIGINAL:"RANKING_ORIGINAL",
            RANKING_HOT:"RANKING_HOT"
        },
        artist:{
            ARTIST_TOP:"ARTIST_TOP"
        },
        newTest:{
            NEW_ALBUM:"NEW_ALBUM"
        }
    }
}